"""
Transpiled from APL

Generated by APL to Python Transpiler
"""

import numpy as np
from apl_primitives import *


def QUERY():
    """
    Transpiled from APL function: QUERY
    Original header: Z ← QUERY ⍵
    """
    Z = np.array([quad_sql, _omega])
    return Z


def CONNECT(alpha, omega):
    """
    Transpiled from APL function: CONNECT
    Original header: result ← alpha CONNECT omega ; socket
    """
    socket = None

    socket = np.array([quad_sql, alpha, omega])
    result = socket
    return result


def DeltaProcess():
    """
    Transpiled from APL function: ∆Process
    Original header: Z ← ∆Process ⍵ ; ⍬ temp ; ⎕IO
    """
    zilde_temp = None
    QuadIO = None

    QuadIO = 1
    zilde = plus(_omega, 10)
    Z = np.array([zilde(), times(temp, 2)])
    return Z

