"""
Transpiled from APL

Generated by APL to Python Transpiler
"""

import numpy as np
from apl_primitives import *


def O(_, Q):
    """
    Transpiled from APL function: O
    Original header: ⍬ p ⍬ ⍷ ⍬ ← ⍺ _ O ? Q A PW pW W ⍷ V ⍴ W 0 W ⊖ V V l l X X ⍕ X X 0 Y Y ⍷ Y 0 Z ⍴ Z Z [ ⍕ [ ← [ \ \ ⍕ \ \ ] ⍴ ] ] 0 ⍷ _ _ _ _ a a ⍴ a a 0 b Pb ⊖ b c 0 c ⍴ c c Pd pd d Pe ⍴ e e f ⍕ f g Pg 0 g g 0 h ⍕ h h ← h pi i j ⍴ j ⊖ j 0 k Pk ⍕ k ← k k m ⊖ q ⍕ q ⊖ p ⍷ p q Pq u u r r r ⊖ r r s s s ⍕ s t t ⍴ t t 0 v v u ⍕ u ← u x pv ⍴ v v w
    """
    return ⍬ p ⍬ ⍷ ⍬


def pi(h, i):
    """
    Transpiled from APL function: pi
    Original header: 0 h ⍕ h h ← h pi i j ⍴ j ⊖ j 0 k Pk ⍕ k ← k k m ⊖ q ⍕ q ⊖ p ⍷ p q Pq u u r r r ⊖ r r s s s ⍕ s t t ⍴ t t 0 v v u ⍕ u ← u x pv ⍴ v v w w pw ⍕ w ⍷ w x z z y ⍕ y y { { z z ⊖ z ⍷ z z P { p { ← { | | | ⍕ ⍴ ~ ~ ~ ⍴ ~ ~ p p ⍴ ≤ ≤ ⊖ ⍷ ¨ ¨ ⍴ ¨ ← ¨ P ⍕ ← < 0 < ⍴ < ⊖ < ≤ ≤ 0 ∨ ∨ = = p = ⊖ = ≥ p ≥ ← ≥ > > > ← > ≠ 0 ≠ ≠ ⍕ ≠ ? ⍕ ? ⍴ ∨ ⊖ ∨ ∨ ∧
    """
    return 0 h ⍕ h h


def k(k, m):
    """
    Transpiled from APL function: k
    Original header: 0 k Pk ⍕ k ← k k m ⊖ q ⍕ q ⊖ p ⍷ p q Pq u u r r r ⊖ r r s s s ⍕ s t t ⍴ t t 0 v v u ⍕ u ← u x pv ⍴ v v w w pw ⍕ w ⍷ w x z z y ⍕ y y { { z z ⊖ z ⍷ z z P { p { ← { | | | ⍕ ⍴ ~ ~ ~ ⍴ ~ ~ p p ⍴ ≤ ≤ ⊖ ⍷ ¨ ¨ ⍴ ¨ ← ¨ P ⍕ ← < 0 < ⍴ < ⊖ < ≤ ≤ 0 ∨ ∨ = = p = ⊖ = ≥ p ≥ ← ≥ > > > ← > ≠ 0 ≠ ≠ ⍕ ≠ ? ⍕ ? ⍴ ∨ ⊖ ∨ ∨ ∧ ∧ P ∧ p ∧ ⍕ ∧ ⍷ ∧ × × × ⍕ ×
    """
    return 0 k Pk ⍕ k


def x(u, pv):
    """
    Transpiled from APL function: x
    Original header: v u ⍕ u ← u x pv ⍴ v v w w pw ⍕ w ⍷ w x z z y ⍕ y y { { z z ⊖ z ⍷ z z P { p { ← { | | | ⍕ ⍴ ~ ~ ~ ⍴ ~ ~ p p ⍴ ≤ ≤ ⊖ ⍷ ¨ ¨ ⍴ ¨ ← ¨ P ⍕ ← < 0 < ⍴ < ⊖ < ≤ ≤ 0 ∨ ∨ = = p = ⊖ = ≥ p ≥ ← ≥ > > > ← > ≠ 0 ≠ ≠ ⍕ ≠ ? ⍕ ? ⍴ ∨ ⊖ ∨ ∨ ∧ ∧ P ∧ p ∧ ⍕ ∧ ⍷ ∧ × × × ⍕ × ← × × 0 ÷ P ÷ p ÷ ⍴ ÷ ÷ ? ? ? ? ∊ ∊ P ⍵ p ⍵ ← ⍵ ↑ ↑ ∊ ∊ ⍷ ∊ ⍴ ⍴ ⍴ ⍕ ⍴ ~ ~ ⍴ ~
    """
    return v u ⍕ u


def p(P, p):
    """
    Transpiled from APL function: p
    Original header: ⍕ ← 0 P p ⊖ ⍕ p ⍴ ⊖ 0 ⍴ ⊖ ⊖ ⍕ p ⍕ ← ⊖ ← 0 p ← P ⍕ ⍷ ⍴ ⊖ p ⍷ p ← ← 0 P p ⍕ ⊖ ⍕ ⍴
    """
    ⍕ = ⊖ = ⍕ = rho(0, ⍷(0, ⍷(p, ⍷(0, reverse_first(shape(reverse_first(⍷(⍷(reverse_first(reverse_first(p)))))))))))
    return ⍕


def P3(C, P4):
    """
    Transpiled from APL function: P3
    Original header: ⍕ 1 2 ⍷ C ← C 3 P3 ⍕ 3 3 P4 ⊖ 4 5 5 ⊖ 5 6 p6 ⍷ 6 7 7 7 ⍷ 7 7 8 8 ⍕ 8 9 9 ⍴ 9 ⊖ 9 0 : ⊖ : ⍷ : ; ⍷ ; ; < p < < = = = ← = = > > ⍴ > ⊖ > ⍷ > 0 ? P ? ⊖ ? ⍷ ? P ⍷ A A A ⍕ A ← A A B ⍕ B C 0 C PC 0 F F ⍴ D ⊖ D E 0E PE pE ⍷ E F H H F ⍕ F F G 0 G PG ⊖ G G H ⍕ I ⍴ I H ⍕ H H I pI L L I J J J ← J J 0 K PK ⍕ K M pM pL ⍴ L L M PM N ← N ← M M N N ⍕ N N N N U U O 0 O O
    """
    ⍷ = None
    < p < < = = = ← = = > > ⍴ > ⊖ > ⍷ > 0 ? P ? ⊖ ? ⍷ ? P ⍷ A A A ⍕ A ← A A B ⍕ B C 0 C PC 0 F F ⍴ D ⊖ D E 0E PE pE ⍷ E F H H F ⍕ F F G 0 G PG ⊖ G G H ⍕ I ⍴ I H ⍕ H H I pI L L I J J J ← J J 0 K PK ⍕ K M pM pL ⍴ L L M PM N ← N ← M M N N ⍕ N N N N U U O 0 O O = None

    return ⍕ 1 2 ⍷ C


def A(A, B):
    """
    Transpiled from APL function: A
    Original header: A A ⍕ A ← A A B ⍕ B C 0 C PC 0 F F ⍴ D ⊖ D E 0E PE pE ⍷ E F H H F ⍕ F F G 0 G PG ⊖ G G H ⍕ I ⍴ I H ⍕ H H I pI L L I J J J ← J J 0 K PK ⍕ K M pM pL ⍴ L L M PM N ← N ← M M N N ⍕ N N N N U U O 0 O O O ⍕ O ⍷ O O P P ⊖ P ⍷ P P 0 Q PQ ⍴ Q ⊖ Q ⍷ Q Q pR ⍴ R ⊖ R S S S S S T T T ⍕ T T ⍷ V ← V ← U U V V ⍕ V pX X W 0 W W ⍕ W X X ← Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z
    """
    return A A ⍕ A


def J(J, K):
    """
    Transpiled from APL function: J
    Original header: J J J ← J J 0 K PK ⍕ K M pM pL ⍴ L L M PM N ← N ← M M N N ⍕ N N N N U U O 0 O O O ⍕ O ⍷ O O P P ⊖ P ⍷ P P 0 Q PQ ⍴ Q ⊖ Q ⍷ Q Q pR ⍴ R ⊖ R S S S S S T T T ⍕ T T ⍷ V ← V ← U U V V ⍕ V pX X W 0 W W ⍕ W X X ← Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z pZ ⊖ Z [ P [ [ ⍕ [ ⍷ [ P \ ← \ ⍕ ] ⍷ ← ⍷ ] ] ⍕ ⍙ p ∊ P T
    """
    return J J J


def M(N, M):
    """
    Transpiled from APL function: M
    Original header: M PM N ← N ← M M N N ⍕ N N N N U U O 0 O O O ⍕ O ⍷ O O P P ⊖ P ⍷ P P 0 Q PQ ⍴ Q ⊖ Q ⍷ Q Q pR ⍴ R ⊖ R S S S S S T T T ⍕ T T ⍷ V ← V ← U U V V ⍕ V pX X W 0 W W ⍕ W X X ← Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z pZ ⊖ Z [ P [ [ ⍕ [ ⍷ [ P \ ← \ ⍕ ] ⍷ ← ⍷ ] ] ⍕ ⍙ p ∊ P T ÷ ⍴ x ⍳
    """
    0
    return M PM N


def M(M, N):
    """
    Transpiled from APL function: M
    Original header: N ← M M N N ⍕ N N N N U U O 0 O O O ⍕ O ⍷ O O P P ⊖ P ⍷ P P 0 Q PQ ⍴ Q ⊖ Q ⍷ Q Q pR ⍴ R ⊖ R S S S S S T T T ⍕ T T ⍷ V ← V ← U U V V ⍕ V pX X W 0 W W ⍕ W X X ← Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z pZ ⊖ Z [ P [ [ ⍕ [ ⍷ [ P \ ← \ ⍕ ] ⍷ ← ⍷ ] ] ⍕ ⍙ p ∊ P T ÷ ⍴ x ⍳
    """
    0
    l
    return N


def U(V, U):
    """
    Transpiled from APL function: U
    Original header: ⍕ T T ⍷ V ← V ← U U V V ⍕ V pX X W 0 W W ⍕ W X X ← Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z pZ ⊖ Z [ P [ [ ⍕ [ ⍷ [ P \ ← \ ⍕ ] ⍷ ← ⍷ ] ] ⍕ ⍙ p ∊ P T ÷ ⍴ x ⍳
    """
    0
    l = shape(rho(FC, rho(RL, rho(PW, np.array([PR, rho(0, np.array([LX, rho(L, rho(TZ, less_equal(SVE, shape(NLT))))]))])))))
    return ⍕ T T ⍷ V


def U(U, V):
    """
    Transpiled from APL function: U
    Original header: V ← U U V V ⍕ V pX X W 0 W W ⍕ W X X ← Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z pZ ⊖ Z [ P [ [ ⍕ [ ⍷ [ P \ ← \ ⍕ ] ⍷ ← ⍷ ] ] ⍕ ⍙ p ∊ P T ÷ ⍴ x ⍳
    """
    0
    l = shape(rho(FC, rho(RL, rho(PW, np.array([PR, rho(0, np.array([LX, rho(L, rho(TZ, less_equal(SVE, shape(NLT))))]))])))))
    return V


def Y(Y, X):
    """
    Transpiled from APL function: Y
    Original header: ⍕ W X X ← Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z pZ ⊖ Z [ P [ [ ⍕ [ ⍷ [ P \ ← \ ⍕ ] ⍷ ← ⍷ ] ] ⍕ ⍙ p ∊ P T ÷ ⍴ x ⍳
    """
    0
    l = shape(rho(FC, rho(RL, rho(PW, np.array([PR, rho(0, np.array([LX, rho(L, rho(TZ, less_equal(SVE, shape(rotate_first(NLT, np.array([ABSTRACT, D, AP2WSM, L0, divide(Z, np.array([TNCP, divide(N, np.array([CODE, L, P]))]))]))))))]))])))))
    return ⍕ W X X


def X(X, Y):
    """
    Transpiled from APL function: X
    Original header: Y ⊖ Y ← X X 0 Y PY ⍴ Y ] ] Z Z pZ ⊖ Z [ P [ [ ⍕ [ ⍷ [ P \ ← \ ⍕ ] ⍷ ← ⍷ ] ] ⍕ ⍙ p ∊ P T ÷ ⍴ x ⍳
    """
    0
    l = shape(rho(FC, rho(RL, rho(PW, np.array([PR, rho(0, np.array([LX, rho(L, rho(TZ, less_equal(SVE, shape(rotate_first(NLT, np.array([ABSTRACT, D, AP2WSM, L0, divide(Z, np.array([TNCP, divide(N, np.array([CODE, L, PRE, T, TAB]))]))]))))))]))])))))
    return Y ⊖ Y


def IS(N, MESSAGE):
    """
    Transpiled from APL function: IS
    Original header: , N ) IS MESSAGE TOKENS ; EXCESS TOKENS ARE IGNORED . ⍪ ( ⍵ ⍙ - TNCP IS TABLENAME [ CODEPREFIX ] ; ⍵ P : ⌹ ⍙ IF TNCP IS SIMPLE THEN IT IS BOTH NAME AND PREFIX . ⌹ P 4 N ⍙ - ALL IBM CODE PREFIXES MUST BE 'AP2W' , WSNAME N J ⌹ ⍙ - THE MESSAGE TABLE HAS A NUMBER ( ⌹ N , ' ' ) FOLLOWED BY MESSAGE TEXT . ⌹ L ⊇ ⍙ '°' MARKS POSITIONS FOR TOKENS ; EXTRA MARKERS ARE FILLED WITH '**' ⊇ P 6 n ⍙ '⍖' SEPARATES MESSAGE FROM 'MORE' INFORMATIONn J ⌹ ⍙ - THE GLOBAL VARIABLE 'MORE' IS GIVEN THE CODE AND THE 'MORE' TEXT . ⌹ D N ⍙ - IF TABLE DOES NOT EXIST OR N IS INVALID , RETURN MESSAGE 999 N n ⍙ n . ⍪ ⍙ EXECUTION PROPERTIES : NON - SUSPENDABLE - ⍪ D N ⍙ ON INVALID ARGUMENTS , SUSPENSION IN THE CALLING FUNCTION IS : N ( ⍵ ⍙ PRODUCED EXPLICITLY , VIA ⍴ ES : ⍵ P 4 N ⍙ VALENCE ERROR ON MISSING LEFT ARGUMENTN P 6 n ⍙ DOMAIN ERROR ON EMPTY RIGHT ARGUMENT 'N' n P : ⌹ ⍙ RANK ERROR ON LEFT ARGUMENT ( MUST BE VECTOR ) ⌹ P : ⌹ ⍙ OR PRODUCED IMPLICITLY , VIA A FAILED OPERATION : ⌹ ! P 4 N ⍙ DOMAIN ERROR ON NUMERIC LEFT ARGUMENT N P 8 ⍵ ⍙ RANK ERROR OR AXIS ERROR ON MESSAGE TABLE ⍵ P 2 . ⍙ N MAY BE ANY TYPE AND RANK , BUT NOT EMPTY . l ← P > S ( M ) / '                ⍙ VALENCE ERROR  &               TNCP        ' ( F S ( ⍪ ) / ) ⍵ ⍙ DOMAIN ERROR ⍵ ) * B S ( h ) / + . ⍙ RANK ERROR . + ,
    """
    EXCESS TOKENS ARE IGNORED . ⍪ ( ⍵ ⍙ - TNCP IS TABLENAME [ CODEPREFIX ] = None
    ⍵ P : ⌹ ⍙ IF TNCP IS SIMPLE THEN IT IS BOTH NAME AND PREFIX . ⌹ P 4 N ⍙ - ALL IBM CODE PREFIXES MUST BE 'AP2W' , WSNAME N J ⌹ ⍙ - THE MESSAGE TABLE HAS A NUMBER ( ⌹ N , ' ' ) FOLLOWED BY MESSAGE TEXT . ⌹ L ⊇ ⍙ '°' MARKS POSITIONS FOR TOKENS = None
    EXTRA MARKERS ARE FILLED WITH '**' ⊇ P 6 n ⍙ '⍖' SEPARATES MESSAGE FROM 'MORE' INFORMATIONn J ⌹ ⍙ - THE GLOBAL VARIABLE 'MORE' IS GIVEN THE CODE AND THE 'MORE' TEXT . ⌹ D N ⍙ - IF TABLE DOES NOT EXIST OR N IS INVALID , RETURN MESSAGE 999 N n ⍙ n . ⍪ ⍙ EXECUTION PROPERTIES : NON - SUSPENDABLE - ⍪ D N ⍙ ON INVALID ARGUMENTS , SUSPENSION IN THE CALLING FUNCTION IS : N ( ⍵ ⍙ PRODUCED EXPLICITLY , VIA ⍴ ES : ⍵ P 4 N ⍙ VALENCE ERROR ON MISSING LEFT ARGUMENTN P 6 n ⍙ DOMAIN ERROR ON EMPTY RIGHT ARGUMENT 'N' n P : ⌹ ⍙ RANK ERROR ON LEFT ARGUMENT ( MUST BE VECTOR ) ⌹ P : ⌹ ⍙ OR PRODUCED IMPLICITLY , VIA A FAILED OPERATION : ⌹ ! P 4 N ⍙ DOMAIN ERROR ON NUMERIC LEFT ARGUMENT N P 8 ⍵ ⍙ RANK ERROR OR AXIS ERROR ON MESSAGE TABLE ⍵ P 2 . ⍙ N MAY BE ANY TYPE AND RANK , BUT NOT EMPTY . l ← P > S ( M ) / '                ⍙ VALENCE ERROR  &               TNCP        ' ( F S ( ⍪ ) / ) ⍵ ⍙ DOMAIN ERROR ⍵ ) * B S ( h ) / + . ⍙ RANK ERROR . + , = None



def A(T, ⍙):
    """
    Transpiled from APL function: A
    Original header: , ⍵ ⍙ TOKENS FOR MESSAGE _N ⍵ p V ← T = A . ⍙ FIND TOKEN MARKERS . A C * * B ⍴ t ( / T ) ← ( + / ) _ ⌈ , ( + / ) C N ⍙ ASSIGN TOKENS OR '**' N D P < ⊇ ⍙_____ RETURN MESSAGE ; SET 'MORE' WITH CODE AND MESSAGE ⊇ E p \ ← + T F ⊇ ⍙ LENGTH OF THE MESSAGE NUMBER ⊇ F H G ⍴ t ← ( ⍲ , _ T ) , ( + T H ) T N ⍙ ASSIGN 'MORE' TEXT N I b ← ( ~ \ ⍸ J ) / ⊇ ⍙ DELETE TRAILING BLANKS ⊇ J K b T ← ( T L ) _ T ⍪ ⍙ RETURN MESSAGE TEXT ⍪ L M b T ← ( ~ \ T ⍸ N ) / T ⊇ ⍙ DELETE TRAILING BLANKS ⊇ N O P > → ( P = M Q ) / ⍙ NAME CONFLICT P Q MORE R F , ← N ⍙ ASSIGN M TO 'MORE' N E ) l 2 E ⍱ ( ! ( * , . / 1 3 4 6 7 8 : ; < = > ? B D E G I K M O R S P 0 0 0 1 ERROR DURING OFFER 2 UNABLE TO OFFER 3 'DAT' IS NOT SHARED WITH AP127
    """
    SET 'MORE' WITH CODE AND MESSAGE ⊇ E p \ ← + T F ⊇ ⍙ LENGTH OF THE MESSAGE NUMBER ⊇ F H G ⍴ t ← ( ⍲ , _ T ) , ( + T H ) T N ⍙ ASSIGN 'MORE' TEXT N I b ← ( ~ \ ⍸ J ) / ⊇ ⍙ DELETE TRAILING BLANKS ⊇ J K b T ← ( T L ) _ T ⍪ ⍙ RETURN MESSAGE TEXT ⍪ L M b T ← ( ~ \ T ⍸ N ) / T ⊇ ⍙ DELETE TRAILING BLANKS ⊇ N O P > → ( P = M Q ) / ⍙ NAME CONFLICT P Q MORE R F , ← N ⍙ ASSIGN M TO 'MORE' N E ) l 2 E ⍱ ( ! ( * , . / 1 3 4 6 7 8 : = None
    < = > ? B D E G I K M O R S P 0 0 0 1 ERROR DURING OFFER 2 UNABLE TO OFFER 3 'DAT' IS NOT SHARED WITH AP127 = None

    return , ⍵ ⍙ TOKENS FOR MESSAGE _N ⍵ p V


def ⍙(J, DELETE):
    """
    Transpiled from APL function: ⍙
    Original header: T N ⍙ ASSIGN 'MORE' TEXT N I b ← ( ~ \ ⍸ J ) / ⊇ ⍙ DELETE TRAILING BLANKS ⊇ J K b T ← ( T L ) _ T ⍪ ⍙ RETURN MESSAGE TEXT ⍪ L M b T ← ( ~ \ T ⍸ N ) / T ⊇ ⍙ DELETE TRAILING BLANKS ⊇ N O P > → ( P = M Q ) / ⍙ NAME CONFLICT P Q MORE R F , ← N ⍙ ASSIGN M TO 'MORE' N E ) l 2 E ⍱ ( ! ( * , . / 1 3 4 6 7 8 : ; < = > ? B D E G I K M O R S P 0 0 0 1 ERROR DURING OFFER 2 UNABLE TO OFFER 3 'DAT' IS NOT SHARED WITH AP127 4 ITEM IS EMPTY , ALL ZERO , OR ALL BLANK 5 ARGUMENT MUST BE A VECTOR 6 RIGHT ARGUMENT LENGTH ERROR 7 STATEMENT ITEM MUST BE SIMPLE 8 ARGUMENT MUST BE SCALAR OR VECTOR 9 ARGUMENT MUST NOT BE EMPTY 10 ARGUMENT MUST NOT BE SIMPLE 11 FIRST ITEM IS NOT A CHARACTER STRING 12 CHARACTER STRING LENGTH IS ONE 13 WRONG NUMBER OF ARGUMENTS FOR THIS STATEMENT 14 MESSAGE CODE MUST BE A SIMPLE LENGTH 5 VECTOR15 STACK MUST BE A MATRIX 16 CHART CALL HAS FAILED . RETURN CODE IS : V T x Z ← TAW n ⍙ TRIVIAL APPEND - CALLED BY QUERYn
    """
    < = > ? B D E G I K M O R S P 0 0 0 1 ERROR DURING OFFER 2 UNABLE TO OFFER 3 'DAT' IS NOT SHARED WITH AP127 4 ITEM IS EMPTY , ALL ZERO , OR ALL BLANK 5 ARGUMENT MUST BE A VECTOR 6 RIGHT ARGUMENT LENGTH ERROR 7 STATEMENT ITEM MUST BE SIMPLE 8 ARGUMENT MUST BE SCALAR OR VECTOR 9 ARGUMENT MUST NOT BE EMPTY 10 ARGUMENT MUST NOT BE SIMPLE 11 FIRST ITEM IS NOT A CHARACTER STRING 12 CHARACTER STRING LENGTH IS ONE 13 WRONG NUMBER OF ARGUMENTS FOR THIS STATEMENT 14 MESSAGE CODE MUST BE A SIMPLE LENGTH 5 VECTOR15 STACK MUST BE A MATRIX 16 CHART CALL HAS FAILED . RETURN CODE IS : V T x Z ← TAW n ⍙ TRIVIAL APPEND - CALLED BY QUERYn = None

    return T N ⍙ ASSIGN 'MORE' TEXT N I b


def IS(ARGS, A):
    """
    Transpiled from APL function: IS
    Original header: ⌊ p ⍱ ∘ ∆ | , ⍎ ⍕ ⊂ ∪ ⊢ ⍋ ⍒ ⌹ ⍟ T ∪ T CUR_ ⌹ P > ⍪ ⍙ - CREATES THE STACK ( OR QUEUE ) FOR A SELECT STATEMENT - ⍪ ⌽ 0 ⍙ THE SEQUENCE IS ( PREP OPEN FETCH CLOSE ) . ⊖ D N ⍙ - ARGS IS A NON - SIMPLE 1 OR 2 - ITEM VECTOR OF ( STMT [ VALUES ] ) . N ⍉ D N ⍙ IF ( _VAL ← 1 ARGS ) IS A MATRIX , THE CALL TO SUBFUNCTION OFC_N ! P > ⍪ ⍙ REPEATS THE ( OPEN FETCH CLOSE ) SEQUENCE FOR EACH ROW . ⍪ ⌿ P T ← ⍀ / ( _ ∪ ) n ⍙ FIRST ARGUMENT IS STATEMENT n ⍀ PREP / APL2 \ N T ← ∪ ⍵ ⍙ SELECT VALUE - LIST ( MAY BE EMPTY ) ⍵ ⍝    P   @      ⌽( = ⍛∪   )/→    .       ⍙ SET EMPTY IF MISSING .→               VAL←⍑⍦0     ⍱   P  :      ⌽(# = ⍛ ⍛ _ T   )/ ¤   ⍵ ⍙ ENCLOSE IF MATRIX⍵      ¤               VAL←⍑[2]_VAL⌻   ⌶   d       T   ← T    , _ ,/ l   µ T  ⍵            ⍙ CATENATE (OPEN FETCH CLOSE) SEQUENCES ⍵           ⍲           ⍱   `   
    """
    #    ⍱   ⌻      ⍃            T  ⍭  ⌈  F DA⍄   0         →(# = M←    )/⊥    ←             F              →              ⍭   ←    ⍬   0         →(#  ‿ M⍺    )/⊥    ⍺               TFMT        ⌈   0          ⍭   ←                  ⌊   0         ⊥   ⌈   ←3  _ ⌈     _   P   6      →( ⍭   =∇   )/ ⍖    , ¸    ,∘             ∇                       ∘             ⊖          '   @   $      ∘   T   ←⎕    ⌹ ⌈              ⎕       
    556 = None
    np.array([6, reduce_plus(np.array([6, reduce_plus(555)]))])
    return ⌊ p ⍱ ∘ ∆ | , ⍎ ⍕ ⊂ ∪ ⊢ ⍋ ⍒ ⌹ ⍟ T ∪ T CUR_ ⌹ P > ⍪ ⍙ - CREATES THE STACK ( OR QUEUE ) FOR A SELECT STATEMENT - ⍪ ⌽ 0 ⍙ THE SEQUENCE IS ( PREP OPEN FETCH CLOSE ) . ⊖ D N ⍙ - ARGS IS A NON - SIMPLE 1 OR 2 - ITEM VECTOR OF ( STMT [ VALUES ] ) . N ⍉ D N ⍙ IF ( _VAL


def n(_, ⍙):
    """
    Transpiled from APL function: n
    Original header: ARGS ) IS A MATRIX , THE CALL TO SUBFUNCTION OFC_N ! P > ⍪ ⍙ REPEATS THE ( OPEN FETCH CLOSE ) SEQUENCE FOR EACH ROW . ⍪ ⌿ P T ← ⍀ / ( _ ∪ ) n ⍙ FIRST ARGUMENT IS STATEMENT n ⍀ PREP / APL2 \ N T ← ∪ ⍵ ⍙ SELECT VALUE - LIST ( MAY BE EMPTY ) ⍵ ⍝    P   @      ⌽( = ⍛∪   )/→    .       ⍙ SET EMPTY IF MISSING .→               VAL←⍑⍦0     ⍱   P  :      ⌽(# = ⍛ ⍛ _ T   )/ ¤   ⍵ ⍙ ENCLOSE IF MATRIX⍵      ¤               VAL←⍑[2]_VAL⌻   ⌶   d       T   ← T    , _ ,/ l   µ T  ⍵            ⍙ CATENATE (OPEN FETCH CLOSE) SEQUENCES ⍵           ⍲           ⍱   `   
    """
    #    ⍱   ⌻      ⍃            T  ⍭  ⌈  F DA⍄   0         →(# = M←    )/⊥    ←             F              →              ⍭   ←    ⍬   0         →(#  ‿ M⍺    )/⊥    ⍺               TFMT        ⌈   0          ⍭   ←                  ⌊   0         ⊥   ⌈   ←3  _ ⌈     _   P   6      →( ⍭   =∇   )/ ⍖    , ¸    ,∘             ∇                       ∘             ⊖          '   @   $      ∘   T   ←⎕    ⌹ ⌈              ⎕       
    556 = None
    6 = None
    5 = ⍨ = None
      = 0 = matrix_divide(quad_, ceiling(quad_))
    556 = None
    6 = None
    5 = ⍨ = None
      = 0 = matrix_divide(quad_, ceiling(quad_))
    556 = None
    6 = None
    5 = ⍨ = None
      = 0 = D = F = None
    ARGS = np.array([ARGS, p])
    return ARGS ) IS A MATRIX , THE CALL TO SUBFUNCTION OFC_N ! P > ⍪ ⍙ REPEATS THE ( OPEN FETCH CLOSE ) SEQUENCE FOR EACH ROW . ⍪ ⌿ P T


def M(F, TFMT):
    """
    Transpiled from APL function: M
    Original header: T ⌈ F DA 0 → ( = M ← ) / ← F → ← ⍬ 0 → ( M ⍺ ) / ⍺ TFMT ⌈ 0 ← ⌊ 0 ⌈ ← 3 _ ⌈ _ P 6 → ( = ) / , , ∘ ∘ ⊖ '   @   $      ∘   T   ←⎕    ⌹ ⌈              ⎕       
       
     0556-06-05 ⍞             →             ¢   P  :      ⍖   T   ← ⊆    ⌹ ⌈   [ l   +⊇   ]      ⊆       
       
     06/06/0555  ⊇                         ⍸             →            ⍷   P  :      ¸   T   ← ⌸    ⌹ ⌈   [ l   +⍤   ]      ⌸       
       
     05 05 0555 ⍤                         ⍥   @   .      (( T   =⍣    )/ T   )←⍨     ⍣                            ⍨             .              ←   @       ⊥    ⊖    ∘     ⍖  
     ¸     ' 'F←0' p
    """
    ⍱ = → = DAT_ = ( = < = matrix_divide(quad_, ceiling(quad_))
    556 = None
    6 = None
    5 = ⍨ = None
      = 0 = D = F = None
    ARGS = ARGS = None
    return T ⌈ F DA 0 → ( = M


def M(F, TFMT):
    """
    Transpiled from APL function: M
    Original header: A 0 → ( = M ← ) / ← F → ← ⍬ 0 → ( M ⍺ ) / ⍺ TFMT ⌈ 0 ← ⌊ 0 ⌈ ← 3 _ ⌈ _ P 6 → ( = ) / , , ∘ ∘ ⊖ '   @   $      ∘   T   ←⎕    ⌹ ⌈              ⎕       
       
     0556-06-05 ⍞             →             ¢   P  :      ⍖   T   ← ⊆    ⌹ ⌈   [ l   +⊇   ]      ⊆       
       
     06/06/0555  ⊇                         ⍸             →            ⍷   P  :      ¸   T   ← ⌸    ⌹ ⌈   [ l   +⍤   ]      ⌸       
       
     05 05 0555 ⍤                         ⍥   @   .      (( T   =⍣    )/ T   )←⍨     ⍣                            ⍨             .              ←   @       ⊥    ⊖    ∘     ⍖  
     ¸     ' 'F←0' p
    """
    ⍱ = → = DAT_ = ( = < = DESC = J = 3 = , = # TODO: operator ⍣ with +
    return A 0 → ( = M


def ⍙(C, GET):
    """
    Transpiled from APL function: ⍙
    Original header: F T ← ∘ ( ⍳ [ C ] ⍪ ⍙ GET WORKSPACE MESSAGE ⍪ ∘ AP2WSQL '  `   H      →(3 =⍳   [3 ])/ ⊇              ⍙ AND EXIT IF THERE IS ONE⊇       ⎕  `   H       T   ← ⍦   ⍳  ⍪                 ⍙ GET COMPLETION MESSAGE ⍪       ⍞  `   J      →⍳   [# ]/ n                  ⍙ EXIT IF ' INCOMPLETE ' BIT IS ONn      ¢  `   F       P	   ←⌹                        ⍙ FORCE SIGNAL IF OFFER FAILS ⌹          ⊆  P   4      →  ⍛ $   n                    ⍙ ENSURE OFFERn            ⊇  P  >       L   ←⍣    ⍸   ⍳   ⊇          ⍙ GET MESSAGE ⊇  ⍸              MSG        ⍷  p   ^       T   ←( ⍑ T   ) ,[ ] ,[ ⍦ ] ,   L   n        ⍙ COMPLETION CODE, MESSAGEn  ⌸  `   N      →(  ^.= _ L   )/ .                ⍙ EXIT IF MSG CALL SUCCESSFUL . ⍤  p   T       T   ← ⍦   ( _ L   )N                 ⍙ ELSE CHANGE COMPLETION CODE, N            ⍥  p   \       ⌈   ←  ⍘⍣   ⍣   ( _ L   )         ⍙ AND GET THE ' MSG ' ERROR, PL14659    ⍣              MSG        ⍨  ⌶   h       T   ←( , ⍑ T   ) ,[ ] ,[ ⍦ ] , ⍑ ⌈            ⍙ AND RETURN IT            PL14659        ⍲         S ⍱ ←   "   @S
    ⍱           ⍷    X ⍲ ⍟ ⌹ ⌽ ⊖ ⍉ ! ⌿ ⍀ / \ ⍝ →  ⍱  ¤  ⌻  ⌺ ←  ⍃ ← → ⍺  ⌈  _  ∇  ' ⎕ ⍞ ⊆ ⊇ ⍷ ⍤ ⍥ ⍨ 0 NO MORE MESSAGES T S ⍴ FX 'Z←NAM⍂  @   &      →( _ T   ← $    ⍃   )/           ⍃                            ⍄  0          T   ←⍣    ⍅         ⍅              NAMES       ⌼           ⌸  @      @  ⍱            ⍄    `  ⌼  ⍁  ⍂  ⍄      ⍖         E  T  ³  x  	  ⍊  @  *     ⌹⍙ Z IS A NESTED VECTOR OF FIELDS IN V ⌹      ⍑  @  (     ⍵⍙ L IS LENGTHS OF FIELDS IN VECTOR V⍵        
∇

∇  L   n        ⍙ COMPLETION CODE, MESSAGEn  ⌸  `   N      →(  ^.= _ L   )/ .                ⍙ EXIT IF MSG CALL SUCCESSFUL . ⍤  p   T       T   ← ⍦   ( _ L   )N                 ⍙ ELSE CHANGE COMPLETION CODE, N            ⍥  p   \       ⌈   ←  ⍘⍣   ⍣   ( _ L   )         ⍙ AND GET THE ' MSG ' ERROR, PL14659    ⍣              MSG        ⍨  ⌶   h       T   ←( , ⍑ T   ) ,[ ] ,[ ⍦ ] , ⍑ ⌈            ⍙ AND RETURN IT            PL14659        ⍲         S ⍱ ←   "   @S
    ⍱           ⍷    X ⍲ ⍟ ⌹ ⌽ ⊖ ⍉ ! ⌿ ⍀ / \ ⍝ →  ⍱  ¤  ⌻  ⌺ ←  ⍃ ← → ⍺  ⌈  _  ∇  ' ⎕ ⍞ ⊆ ⊇ ⍷ ⍤ ⍥ ⍨ 0 NO MORE MESSAGES T S ⍴ FX 'Z←NAM⍂  @   &      →( _ T   ← $    ⍃   )/           ⍃                            ⍄  0          T   ←⍣    ⍅         ⍅              NAMES       ⌼           ⌸  @      @  ⍱            ⍄    `  ⌼  ⍁  ⍂  ⍄      ⍖         E  T  ³  x  	  ⍊  @  *     ⌹⍙ Z IS A NESTED VECTOR OF FIELDS IN V ⌹      ⍑  @  (     ⍵⍙ L IS LENGTHS OF FIELDS IN VECTOR V⍵        ⍘  P   @       	   ←  , ⍙    ∇+\ ³   ⊇  ⍙ BEGINNINGS OF FIELDS⊇⍙            ¿¿¿¿            ⍚  P  >       T   ← ³    _µ 	    ∇µ ⍑ x   .  ⍙ PARTITION .  ⍏         E  ⍆  P      @E  ⍱           ⍴     
    ⍏  ⍖  ⍊  ⍑  ⍘  ⍚        ←  ⍮           T ÷ ⍴FX ' Z ← N * ⌹ ⍙ DOES A CONTAIN ONLY NUMERIC DIGITS ? ⌹ P > T ← / , ÷ ⍪ ⊇ ⍙ EXCLUDE E , J NOTATION ⊇ 0 - 123456789 . ⍱
    """
    ⍪ = N = reduce_plus(ravel(reciprocal(⍪(⊇(np.array([⍙, EXCLUDE, catenate(E, np.array([J, ⊇(NOTATION, minus(0, 123456789))]))]))))))
    ⍪ = N = reduce_plus(ravel(reciprocal(⍪(⊇(np.array([⍙, EXCLUDE, catenate(E, np.array([J, ⊇(NOTATION, minus(0, 123456789))]))]))))))
    ⍪ = P = F = ) = ∩ = S = # TODO: operator ⍣ with +
    return F T


def ⍙(x, PARTITION):
    """
    Transpiled from APL function: ⍙
    Original header: x . ⍙ PARTITION . E P E ⍱ ⍴
    """
    UNKNOWN = T = ODBC = None
    ARGS = ARGS = < = ⍣ = N = reduce_plus(ravel(reciprocal(⍪(⊇(np.array([⍙, EXCLUDE, catenate(E, np.array([J, ⊇(NOTATION, minus(0, 123456789))]))]))))))
    ⍪ = P = F = ) = ∩ = S = ⍣ = PUR = ¨ = np.array([3, B])
    ARGS = ARGS = ⍣ = np.array([RE, quad_, F, n, minus(⍙, np.array([RESUME, CALLS, QUE, TO, PROCESS, A, STACK, OF, DATA, ACCESS, REQUESTS, n, quote_quad_input(), F, n, minus(⍙, np.array([QUE, CALLS, OFFER, TO, SHARE, catenate('DAT', np.array([IF, IT, IS, NOT, ALREADY, SHARED, n, P, minus(⍙, np.array([ANY, ERROR, FORCES, AN, EXIT, FROM, QUE, WITH, THE, CUR]))]))]))]))])


def _(P, DAT):
    """
    Transpiled from APL function: _
    Original header: T ← → ← P ⍱ ∘ → ⍬ ⍺ ⌈ ⌊ _ ⍋ '           T  l  	  Z←RE⎕  `   F      n⍙ - RESUME CALLS  QUE  TO PROCESS A STACK OF DATA ACCESS REQUESTS n         ⍞  `   F      n⍙ - QUE CALLS  OFFER  TO SHARE ' DAT ', IF IT IS NOT ALREADY SHARED n          ¢  P   @      ⍙ - ANY ERROR FORCES AN EXIT FROM QUE WITH THE CURRENT CODE,⊆  P   6      n⍙   DATA, AND STACK VALUES IN THE RESULT VECTOR Z n          ⊇  `   B      .⍙ - RESUME REDUCES THE SECOND ITEM OF THE RESULT TO THE RESULT.              ⍸  0        ⍪⍙   OF FETCH REQUESTS ONLY⍪ ⍷  P  >     ⍪⍙ - IF THERE WAS MORE THAN ONE FETCH, A MATRIX IS RETURNED⍪  ⌸  `   L       T   ← T    l   .                      ⍙ PROCESS STACK WITH QUE.   ⍤  p   X       	   ← _µ( ⍛#  ⍘ T   ) _ , l   ⊇                ⍙ S IS PROCESSED OPCODES⊇        ⍥  p   V       	   ←( ⍑⍣   ) ⌸ 	   N                   ⍙ S INDICATES FETCH COMMANDS N         ⍣              FETCH      ⍨  ⌶   j       	   ← 	    ⍩(- ⍛ 	   ) _ ~ ⍩/ 	   n                   ⍙ IF NO FETCHES USE LAST RESULTn      ⍠  p   Z      (#  ⍘ T   )← 	   /#  ⍘ T   .                      ⍙ SELECT FETCH DATA ONLY.      ⌸  `   H      →( = ⍛#  ⍘ T   )/ ⊇                      ⍙ EXIT IF NOTHING ⊇        ⌼  p   X      (#  ⍘ T   )← ,[ ⍦ ]#  ⍘ T                      ⍙ CREATE MATRIX OTHERWISE        ⍁  `   P      →(  ‿  _ ⍛#  ⍘ T   )/                     ⍙ EXIT IF MULTIPLE FETCH⍂  p   X      (#  ⍘ T   )← _#  ⍘ T  ⍵                       ⍙ DECREASE DEPTH IF SINGULAR ⍵       ∘             ⌶      @
    ⍱           ⍷   ⍀ ∘  ' ⎕ ⍞ ⊆ ⊇ ⍸ ⍷ ⍤ ⍥ ⍨ ⍙ → D DAT
    """
    return T


def ⍙(d, RETURNS):
    """
    Transpiled from APL function: ⍙
    Original header: [ ] ) / n ⍙ PROCESS NEXTn ⌈ ⍱ ≤ ⍪ T H FX 'Z←SE   0          T   ←                                                                        P  >      →( _( _ T   )← $   )/⌹           ⍙ SHARE DAT⌹    P   6      ⌽( = ⍸ H   )/   ⍵ ⍙ ENCLOSE IF SIMPLE⍵                        OPTS←,⍑OPTS   @  *       T   ←⍣   ( ⍑    ) , H                       SETOPT      µ           ´  P      @  ⍱            ⍄    0  µ  ¿                 ∩  
           C  T  x  l   ⍴FX  @  *     ⌹⍙ DISPLAY SQL RESULT ← CODE DATA STACK⌹                  n ⍙ n             0         n⍙ NON-SUSPENDABLE n                      n ⍙ n                        l   ←       p   V       T   ←            N                        ⍙ INITIALIZE TO EMPTIES N                                                                                                ⌶   b      →( _( _ T   )←c  ⌺    ~( ⍛ x   ) ⍸ ,3 )/ n      ⍙ CDS MUST BE 3-ITEM VECTOR n                p   T      (  ⍘ T   )← X     ⍘ x  ⍪               ⍙ CODE - GET MESSAGE IF ANY⍪              P   @      (#  ⍘ T   )←#  ⍘ x   .                       ⍙ DATA .  p   X      (3  ⍘ T   )←3  ⍘ x  ⌹                       ⍙ STACK - EMPTY OR DEPTH 3 OR 4⌹          p   T       T   ← ,[ ⍦ ] T  ⍵                          ⍙ DISPLAY DOWN THE SCREEN ⍵            	         C    p      @C  ⍱            ⍄    `  	  
                                         P        T ∪  ⌼  	 ⍴  x  x  $	  ⍭  ⌈ ∪ →  l  l            P  >     ⍪⍙ - CREATES AND PROCESSES A SEQUENCE OF
∇

∇ CK AS 1 COLUMN MATRIXn                  ←   !   @ 3⍱               ‿                 !  "  #  $  %  &  ' ( ) - . 0 2 3 5 6 9 : > B E G I J K R S V L Y T A ⍴ FX 'Z←SQLZ  P  :     ⌹⍙ RETURNS CURRENT CONTENTS OF THE SQLCA CONTROL BLOCK ⌹     [  0          T   ← \   ]         \                           ]                            ^  `   D      →( _( _ T   )← $   )/            ⍙ ENSURE AN OFFER            _  0          T   ←⍣    `         `              SQLCA       X           W  P      @	  ⍱                ⍙  X  Y  Z [  ^  _         3  c           T  TATE ⍴FX ' Z ← d , ⊇ ⍙ RETURNS THE CURRENT VALUE OF SQLSTATE ⊇ e 0 T ← f g f g h D → ( _ ( _ T ) ← ) / ⍙ ENSURE AN OFFER i 0 T ← ⍣ j j SQLSTATE b a P ⍱ b c d e h i k n T 0 'Z←SSIDo  P  >      →( _ T   ← $    p   )/⍵  ⍙ ENSURE AN OFFER ⍵  p                            q  `   B       T   ←⍣   ( ⍑ r   ) ,(  ‿ ⍛ , 0   ) ⍛ ⍑ 0                 r              SSID        m           l  @      @	  ⍱            ⌶      m  n  o  q      u           T  \  l ←STAv             l   ←     w  @   0      ⍙ RETURNS THE STATE WITH A MEANING APPENDED x  `   F      →( _ T   ← $    y   )/           ⍙ ENSURE AN OFFER           y                            z  P  <       T   ←⍣   {    \  ⌹       ⍙ SPEC,REF DAT ⌹   {              STATE      |  P  <      →( _ _ T   )
∇

∇  ⌈          ⍀           -              /            .              \              055        ⍉          ⊖  @      @  ⍱           ≤    ⌺ ⍉ ! ⌿         ⍱           T  x  X ' Z ← TOM 0 ⊇ ⍙ MATRIX GIVEN ANY ARRAY ⊇ . → ( x ← = T ← x ) / d T ← ( ( ( / T ) / ← T ) , _ , T ) T ← → ⍝   P      @	  ⍱            x   ÷ →  ⍱  ¤  ⌻  ⌺ *        ○ →           T  ⍭  X 'Z←TRA⍬  P  >      →( _ T   ← $   ⍺   )/⍵  ⍙ ENSURE AN OFFER ⍵ ⍺                            ⌈  @  *       T   ←⍣   ( ⍑ ⌊   ) , ⍭         ⌊              TRACE      ←           ⍄  @      @-.⍱            X   ⌼ ← → ⍬  ⌈     ∘         	  T  ⍭    x  '  P  >     ⍪⍙ - THE DERIVED FUNCTION (F UNTIL) WILL PROCESS EACH ITEM ⍪ ⎕  @   $      N⍙    IN Q UNTIL AN ERROR OCCURS.N           ⍞  P  :     ⌹⍙ - IF SUCCESSFUL, FUNCTION F MUST RETURN ONE OR MORE ⌹      ¢  P   2      .⍙    ZEROES AS THE FIRST ITEM OF THE RESULT X..              ⊆  0          T   ← ⊇                 ⊇                            ⍸  0         →( = ⍛    )/        ⍷  ⌶   d      ⊥   T   ← T    , ⍑ x   ← ⍭   ( _    )n             ⍙ PROCESS FIRST ITEM n            ⌸  p   T      →( = ⍛    ←      )/⍪              ⍙ EXIT IF LAST ITEM IN STACK⍪           ⍤  `   P      →(  ^.= _ x   )/⊥  ⍪               ⍙ PROCESS NEXT IF NO ERROR ⍪         	 ⊥     ⍖  ⌈  _  `   	   @	  ⍱            ⍄       ∘  ' ⎕ ⍞  ¢  ⊆  ⍸ ⍷  ⌸ ⍤  ⍁     ⍥  0           ABCDEFGHIJKLMNOPQRSTUVWXYZ  ⍠           T < ⍴FX 'Z←X⌸  P  >      →( _ T   ← $    ⌼  
    """
    return [ ] ) / n ⍙ PROCESS NEXTn ⌈ ⍱ ≤ ⍪ T H FX 'Z←SE   0          T   ←                                                                        P  >      →( _( _ T   )← $   )/⌹           ⍙ SHARE DAT⌹    P   6      ⌽( = ⍸ H   )/   ⍵ ⍙ ENCLOSE IF SIMPLE⍵                        OPTS←,⍑OPTS   @  *       T   ←⍣   ( ⍑    ) , H                       SETOPT      µ           ´  P      @  ⍱            ⍄    0  µ  ¿                 ∩  
           C  T  x  l   ⍴FX  @  *     ⌹⍙ DISPLAY SQL RESULT ← CODE DATA STACK⌹                  n ⍙ n             0         n⍙ NON-SUSPENDABLE n                      n ⍙ n                        l   ←       p   V       T   ←            N                        ⍙ INITIALIZE TO EMPTIES N                                                                                                ⌶   b      →( _( _ T   )←c  ⌺    ~( ⍛ x   ) ⍸ ,3 )/ n      ⍙ CDS MUST BE 3-ITEM VECTOR n                p   T      (  ⍘ T   )← X     ⍘ x  ⍪               ⍙ CODE - GET MESSAGE IF ANY⍪              P   @      (#  ⍘ T   )←#  ⍘ x   .                       ⍙ DATA .  p   X      (3  ⍘ T   )←3  ⍘ x  ⌹                       ⍙ STACK - EMPTY OR DEPTH 3 OR 4⌹          p   T       T   ← ,[ ⍦ ] T  ⍵                          ⍙ DISPLAY DOWN THE SCREEN ⍵            	         C    p      @C  ⍱            ⍄    `  	  
                                         P        T ∪  ⌼  	 ⍴  x  x  $	  ⍭  ⌈ ∪ →  l  l            P  >     ⍪⍙ - CREATES AND PROCESSES A SEQUENCE OF
∇

∇ CK AS 1 COLUMN MATRIXn                  ←   !   @ 3⍱               ‿                 !  "  #  $  %  &  ' ( ) - . 0 2 3 5 6 9 : > B E G I J K R S V L Y T A ⍴ FX 'Z←SQLZ  P  :     ⌹⍙ RETURNS CURRENT CONTENTS OF THE SQLCA CONTROL BLOCK ⌹     [  0          T   ← \   ]         \                           ]                            ^  `   D      →( _( _ T   )← $   )/            ⍙ ENSURE AN OFFER            _  0          T   ←⍣    `         `              SQLCA       X           W  P      @	  ⍱                ⍙  X  Y  Z [  ^  _         3  c           T  TATE ⍴FX ' Z


def x(T, ABCDEFGHIJKLMNOPQRSTUVWXYZ):
    """
    Transpiled from APL function: x
    Original header: - . ⍱ X ← → ⍬ ⌈ ∘ T x '  P  >     ⍪⍙ - THE DERIVED FUNCTION (F UNTIL) WILL PROCESS EACH ITEM ⍪ ⎕  @   $      N⍙    IN Q UNTIL AN ERROR OCCURS.N           ⍞  P  :     ⌹⍙ - IF SUCCESSFUL, FUNCTION F MUST RETURN ONE OR MORE ⌹      ¢  P   2      .⍙    ZEROES AS THE FIRST ITEM OF THE RESULT X..              ⊆  0          T   ← ⊇                 ⊇                            ⍸  0         →( = ⍛    )/        ⍷  ⌶   d      ⊥   T   ← T    , ⍑ x   ← ⍭   ( _    )n             ⍙ PROCESS FIRST ITEM n            ⌸  p   T      →( = ⍛    ←      )/⍪              ⍙ EXIT IF LAST ITEM IN STACK⍪           ⍤  `   P      →(  ^.= _ x   )/⊥  ⍪               ⍙ PROCESS NEXT IF NO ERROR ⍪         	 ⊥     ⍖  ⌈  _  `   	   @	  ⍱            ⍄       ∘  ' ⎕ ⍞ ⊆ ⍸ ⍷ ⍤ ⍥ 0 ABCDEFGHIJKLMNOPQRSTUVWXYZ T < ⍴ FX 'Z←X⌸  P  >      →( _ T   ← $    ⌼   )/⍵  ⍙ ENSURE AN OFFER ⍵  ⌼                            ⍁  @  *       T   ←⍣   ( ⍑ ⍂   ) ,<         ⍂              XMLSIZE    ⍨          ⍣  @      @	⍱           ⊥     ⍨  ⍠  ⌸  ⍁      
∇

∇     )/⍪              ⍙ EXIT IF LAST ITEM IN STACK⍪           ⍤  `   P      →(  ^.= _ x   )/⊥  ⍪               ⍙ PROCESS NEXT IF NO ERROR ⍪         	 ⊥     ⍖  ⌈  _  `   	   @	  ⍱            ⍄       ∘  ' ⎕ ⍞ ⊆ ⍸ ⍷ ⍤ ⍥ 0 ABCDEFGHIJKLMNOPQRSTUVWXYZ T < ⍴ FX 'Z←X⌸  P  >      →( _ T   ← $    ⌼   )/⍵  ⍙ ENSURE AN OFFER ⍵  ⌼                            ⍁  @  *       T   ←⍣   ( ⍑ ⍂   ) ,<         ⍂              XMLSIZE    ⍨          ⍣  @      @	⍱           ⊥     ⍨  ⍠  ⌸  ⍁      
∇
'
    """
    return - . ⍱ X

